name: Python CI/CD - Run All Files and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run all Python scripts
      run: |
        echo "Running all .py files..."
        find . -name "*.py" -not -path "./.venv/*" -not -path "./venv/*" -not -path "./.git/*" | while read file; do
          echo "▶ Running $file"
          python "$file" || exit 1
        done

    - name: Build the Project
      run: |
        pip install build
        python -m build
